### ISSUE TITLE
PATCH /todos/1 results in a 404.

### ISSUE THREAD

**Issue by poetaster** [gleam-lang/example-todomvc#29]
After creation, editing yields:

```
XHRPATCH
http://localhost:3000/todos/1
[HTTP/1.1 404 Not Found 2ms]
```
Is this not finished or has something broken?

gleam 0.32.4
matcha 0.16.0

**Comment by poetaster** [comment]
The full Info report from the backend:
```
=INFO REPORT==== 21-Nov-2023::13:59:13.706936 ===
404 PATCH /todos/1
```
> Request(Patch, [#("accept", "*/*"), #("accept-encoding", "gzip, deflate, br"), #("accept-language", "en,de;q=0.7,en-US;q=0.3"), #("connection", "keep-alive"), #("content-length", "70"), #("content-type", "application/x-www-form-urlencoded; charset=UTF-8"), #("cookie", "_xsrf=2|b3ced82f|4803888d35d0ac48e817555d17b3af4b|1699862509; username-localhost-8888=2|1:0|10:1699862546|23:username-localhost-8888|204:eyJ1c2VybmFtZSI6ICIxZWQyMmI4MzNjMjk0Y2UxODk5ZjcyNzEzN2E4M2U3ZSIsICJuYW1lIjogIkFub255bW91cyBLYWxsaWNob3JlIiwgImRpc3BsYXlfbmFtZSI6ICJBbm9ueW1vdXMgS2FsbGljaG9yZSIsICJpbml0aWFscyI6ICJBSyIsICJjb2xvciI6IG51bGx9|7873d7928a6dbcdda005c6d2ad7fc1c14951a1541d027f954218f92015edb5ef; uid=SFM1MTI.MQ.3pcWLTIrsCjNDNmPSE0mziebVjt6MFfflVQX3Q2xp9bUmnBiUv53mh4XAiB2y74jmwcS8QNEhZcZf92G2rme2A"), #("dnt", "1"), #("host", "localhost:3000"), #("hx-current-url", "http://localhost:3000/"), #("hx-request", "true"), #("hx-target", "item-1"), #("hx-trigger-name", "content"), #("origin", "http://localhost:3000"), #("referer", "http://localhost:3000/"), #("sec-fetch-dest", "empty"), #("sec-fetch-mode", "cors"), #("sec-fetch-site", "same-origin"), #("user-agent", "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0")], Connection(//fn(a) { ... }, 8000000, 32000000, 1000000, "27434b28994f498182d459335258fb6e", "/tmp/gleam-wisp/d5ZeU9DknZKBx0ZA"), Http, "localhost", None, "/todos/1", None)

**Comment by lpil** [comment]
Thank you for the report! There was a bug in the SQL which I have since fixed.

**Comment by poetaster** [comment]
> Thank you for the report! There was a bug in the SQL which I have since fixed.

Ok, that does fix the patch issue. I noticed that clicking on the page (no focused on the input field) still sends patch to the backend. I'll have a look at the htmx.

EDIT: If you edit a todo, it doesn't lose focus when you hit enter. Try editing the previous item, and it loop patches continuously.  Looks like a missing form element. 
```
    <button
      class="destroy"
      hx-delete="/todos/1"
      hx-target="#item-1"
    ></button>
    </form>

    <form
      class="todo-mark"
      hx-patch="/todos/1/completion"
      hx-target="#item-1"
      hx-swap="outerHTML"
    >
      <button></button>
    </form>
  </div>
```
But trying to balance the form doesn't help.
