### ISSUE TITLE
Is there a write up about this?  Documentation?

### ISSUE THREAD

**Issue by bartonhammond** [gleam-lang/example-todomvc#33]
I think this is a great example of using HTMX and Sqlite together with Gleam.  I would really appreciate if there was a write up about it. Thanks for making it available!

**Comment by lpil** [comment]
What would this write up include?

**Comment by bartonhammond** [comment]
I don't know Gleam - just learning.  So if I were to write this application myself, where would I start?  I'd like to see the steps that were taken to build it.  Like a replay of the commits w/ explanations.  I'd love to see how to do this in TDD since I see there are tests. I think it's very interesting mixing this "macha" and "htmx".  That's totally new to me.  I'm going through the code and some is pretty clear but I don't know "wisp" either so I'm a little lost how it all ties together.  Like I said, having a tutorial and started from a blank slate, like the "vars" example would be fantastic.

**Comment by lpil** [comment]
This is just an example codebase rather than a tutorial, so there won't be anything here. Wisp has some tutorials and community members have made some too, that'd be a good place to go.
